### ISSUE TITLE
identifying analog vs AES XLR cables

### ISSUE THREAD

**Issue by EG-tech** [amiaopensource/cable-bible#10]
Casual research indicates that because of the differences in electrical impedance, one could safely use digital AES-3 cables with XLR connectors to make analog connections, but _not_ use analog XLR cables to make digital AES/EBU connections (at least not without introducing extra noise/fuzziness into the digital audio). 

This is a crucial difference to know - so if one comes across a random XLR cable, how does one identify that it is analog or AES-3?

**Comment by eddycolloton** [comment]
Plus one on this question!

**Comment by retokromer** [comment]
See https://github.com/amiaopensource/cable-bible/issues/33 as well.

**Comment by retokromer** [comment]
I guess you mean the 110 Ω cable? In my experience, they often have gold plated connectors. And, in doubt, I do measure the impedance, but this may not be an orthodox approach.

**Comment by retokromer** [comment]
I spoken with a few old sound technicians and they all confirmed me that there is not a canonical sign that distinguishes the digital ones. The gold plated connectors may be a clue. But measuring the impedance seems to be common practice in doubt. Hope this helps!

**Comment by EG-tech** [comment]
Thanks @retokromer! Yes, I was basically wondering whether there was any external way of identifying the impedance on an XLR cable, and had seen some tips about the gold plated connectors but it definitely is not true that all 110 Ω cables have them. So it is good just to confirm that there's basically no way to be sure without directly measuring. I will add info to the XLR modules for Balanced Audio and AES-3 to clarify the impedance issue.
