### ISSUE TITLE
License.md

### ISSUE THREAD

**Issue by ablwr** [amiaopensource/cable-bible#11]
I love this resource very much. Is this licensed under Creative Commons, MIT, other...?

**Comment by MIAPtech** [comment]
thanks for raising this question, Ashley, i had not thought about copyright/licensing! after doing some research i've decided to license The Cable Bible with a CC 4.0 Share-Alike, so as to hopefully be able to take advantage of some Wikimedia images. I have also temporarily removed all images from the doc while I sort out a reasonable system for uploading and/or attributing new images.

**Comment by ablwr** [comment]
Thanks @MIAPtech!

I wasn't worried about the images because I assumed this is under "fair use." But I was going to take the information and images here and re-use them for my own "fair use." Let me know how I can help!

**Comment by ablwr** [comment]
I hope I am not causing trouble for you!

**Comment by MIAPtech** [comment]
no no! i had no qualms whatsoever about using a wikicommons image of a SCART connector as fair use, but i wanted to start from scratch with images of my own anyway - the more to encourage people to take and upload their own!
