### ISSUE TITLE
Interesting cable not mentioned in current list

### ISSUE THREAD

**Issue by travislwagner** [amiaopensource/cable-bible#16]
Found this cable as part of the Cortical S Systematics Micro-pod technology and thought it might be worthy of inclusion

![tumblr_mxo7qnjo8z1qzdu6mo1_500](https://cloud.githubusercontent.com/assets/23507589/20361453/9cfd173c-ac05-11e6-9de2-5f42f313f20a.jpg)

**Comment by ablwr** [comment]
👍 +1 important

**Comment by todrobbins** [comment]
WHOA +1
