### ISSUE TITLE
[wish] formula for cable-bible

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/cable-bible#22]
This way, any time
```
brew update
brew upgrade
```
is run, also `cable-bible` will be updated to the lastest release, if needed.

**Comment by ablwr** [comment]
Does cable-bible also work offline, as ffmprovisr? If not you can make an issue and I can make the necessary optimizations.

**Comment by retokromer** [comment]
I think so. – At least I haven’t seen personally a point which would break…

**Comment by MIAPtech** [comment]
pinout links wouldn't look so nice if you didn't have a markdown viewer and maybe google fonts would break, but otherwise all internal so can't see why not?

**Comment by ablwr** [comment]
Google fonts breaks for ffmprovisr too but still looks MIGHTY FIIIIIINE!

**Comment by retokromer** [comment]
@MIAPtech: It depends on the browser! I've tested with one that – visibly – knows also markdown. I just checked now some others… with various results.

**Comment by MIAPtech** [comment]
Is there an example anywhere of a Homebrew formula that just downloads and unzips the tarball to a useful/user-set local directory? Been looking at the scripts in homebrew-amiaos and seems like it should be simple but the fact that cable-bible doesn't really need to be "installed" is tripping me up

**Comment by retokromer** [comment]
Hmm… It should just be copied. I saw something like `buildpath` that I presume fit’s the purpose, but it’s possibly simpler to use an external command (Ruby or Shell).

**Comment by retokromer** [comment]
I think the easiest is just an external shell command: `cp`.

**Comment by MIAPtech** [comment]
```
class CableBible < Formula
  homepage 'https://github.com/amiaopensource/cable-bible'
  url "https://github.com/amiaopensource/cable-bible/archive/v2017-02-27.tar.gz"
  sha256 "9fd5a792dc0973721abe08963775072462ce5ee0f1c115b6cfb7ca38c8420902"

  def install
     system "cp -a ../ /usr/local/"
  end
end
```
Copying to any location other than one prefixed by `/usr/local` returns homebrew Empty Installation error and rejects unzip/copying. In `/usr/local`, empty installation error still displays but directory is successfully downloaded/unzipped/copied anyway.

Also, on updates would this create a completely new directory and version any time there was a new `cable-bible` release; e.g. you'd end up with separate `cable-bible-2017-02-27` and `cable-bible-2018-03-01` directories, etc etc, after a `brew update && brew upgrade`? Seems less desirable than updating/replacing files in place.

Unsure how to fix this right now, or which /usr/local directory would be most desirable for the repo to live in (Cellar?)

**Comment by retokromer** [comment]
I cannot check this now, but will as soon as possible. I don’t think multiple directories is desirable.

**Comment by retokromer** [comment]
I guess `~/Documents` would be a better choose. Any thoughts?

**Comment by retokromer** [comment]
Perhaps `post_install` allows copying onto another location. – Untested!

**Comment by retokromer** [comment]
Resolved in https://github.com/amiaopensource/homebrew-amiaos/pull/42 by @MIAPtech . Thanks a lot!
