### ISSUE TITLE
add u-matic dub cable

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/cable-bible#31]
sony brand name vdc-5 ; 7-pin; Y/c-688

will send relevant links...

**Comment by EG-tech** [comment]
working on adding descriptions and pinouts for both the Y/C-688 and component Y'P<sub>B</sub>P<sub>R</sub> flavors of 7-pin "dub" thanks to the Captain's Journal... but could still use some pics of such cables and ports if you've got 'em!

**Comment by EG-tech** [comment]
could still use a pic of an actual 7-pin dub cable if anyone's got one, but descriptions added!
