### ISSUE TITLE
pinouts are a mess

### ISSUE THREAD

**Issue by EG-tech** [amiaopensource/cable-bible#35]
A long-lingering result of the switch to ffmprovisr's codebase is that the internal linking from any module to its relevant connector/protocol pinout in pinouts.md is broken: in the online version, browsers just want to download the pinouts.md file. Offline, pinout images are live-linked to pinouts.ru so don't display even if opened properly with a browser with markdown viewing.

options:
- upload all pinout images to the repo to enhance stability/remove reliance on pinouts.ru hosting (should be done no matter what, to match in-repo connector images)
- re-structure pinouts.md to an HTML page and re-establish internal links
- hold off for dynamic restructure of entire site, a la this [ffmprovisr discussion](https://github.com/amiaopensource/ffmprovisr/issues/309), to allow for more modular addition and linking of pinouts

**Comment by todrobbins** [comment]
at least the first.

**Comment by ablwr** [comment]
happy to spend a day pair-programming our way to a jekyll future for cable-bible if that's what it comes to!

**Comment by ablwr** [comment]
Still interested in hackajam'ing this to a solution, mini-hackathon

**Comment by EG-tech** [comment]
Fully on board with a hack-a-thon but also unlikely that I'll have time until the summer! 😩

**Comment by EG-tech** [comment]
Resolved!

- refactored pinouts.md into a pinouts.html page, re-established all internal links
- uploaded all pinouts image into repo to enhance stability, updated internal links accordingly
- cleaned up images folder while I was at it

Restructuring the whole site to allow for more modular/less intimidating updating is still another question, but worth of its own issue.

I plan to add some more info on SCSI connectors in the next day or two thanks to this thread
https://twitter.com/bitsgalore/status/1004333430350536705

so am going to hold off on creating a new release and updating homebrew tap until that's done

**Comment by ablwr** [comment]
🤘
