### ISSUE TITLE
II. Audio B. Digital Audio 4. TDIF

### ISSUE THREAD

**Issue by agentglover** [amiaopensource/cable-bible#39]
Under TDIF, the Bible states: "The Tascam Digital Interface Format is a proprietary protocol and connector, therefore seen exclusively with Tascam devices...."

Tascam licenses this format to many other manufacturers.  In fact, if you click on the image for the DB-25 connector shown, TDIF can clearly be seen on a Yamaha device.

**Comment by EG-tech** [comment]
Thank you for catching this! I've corrected the text to reflect that while proprietary, the protocol is not exclusive.

**Comment by agentglover** [comment]
Thank you!
