### ISSUE TITLE
move and expand MIDI protocol module

### ISSUE THREAD

**Issue by EG-tech** [amiaopensource/cable-bible#47]
technically MIDI isn't an audio signal per se, so should probably be under "Data"

there's also a bunch more connectors besides the older/standard 5-pin DIN, which might actually help clarify the signal type and when/what/why MIDI comes into play (e.g. USB/FireWire/ethernet jacks)

see: https://en.wikipedia.org/wiki/MIDI#Alternative_hardware_transports

**Comment by retokromer** [comment]
+1

**Comment by EG-tech** [comment]
resolved in 2c484e61bf73cabd585faad8d63beab64c89d9ed

**Comment by retokromer** [comment]
@EG-tech You could make a new release. Then I will update the Homebrew formula to install the resource locally. Thank you!

**Comment by EG-tech** [comment]
I plan on it! But I have another PR I am about to submit that I would like some review by the community/committee on. If that reaches quick consensus, I would like to package them in a release together, but if more discussion is necessary, I will indeed just make a new release!
