### ISSUE TITLE
add pictures of connectors, ports and pinouts

### ISSUE THREAD

**Issue by EG-tech** [amiaopensource/cable-bible#7]
Analog Video:
- [x] Composite
- [x] Component YPbPr
- [x] S-Video
- [x] RGBS
- [x] RGBVH

Digital Video:
- [x] SDI
- [x] FireWire
- [x] DVI
- [x] DisplayPort
- [x] HDMI

Integrated Analog/Digital Video:
- [x] DVI-I

Analog Audio:
- [x] Balanced wiring
- [x] Unbalanced wiring

Digital Audio:
- [x] AES-3
- [x] S/PDIF
  - [x] optical wiring
- [x] MIDI
- [x] TDIF
- [x] ADAT

Parallel Data:
- [x] PATA
- [x] Parallel SCSI
- [x] IEEE 1284 Parallel Port

Serial Data:
- [x] RS-232
- [x] RS-422
- [x] SAS (Serial SCSI)
- [x] SATA
- [x] Apple Desktop Bus
- [x] PS/2
- [x] USB
  - [x] USB 2.0
  - [x] USB 3.0
  - [x] USB 3.1
- [x] FireWire
  - [x] FireWire 400
  - [x] FireWire 800
- [x] ThunderBolt
  - [x] ThunderBolt 1 and 2
  - [x] ThunderBolt 3
- [x] HDBaseT

**Comment by todrobbins** [comment]
How about https://prodzone-tripplite.netdna-ssl.com/shared/product-images/lg/N202200BL-FRONT-L.jpg for HDBaseT? If yes, I'll send a pull request.

**Comment by EG-tech** [comment]
*all* listed connectors finally have sample images, and, I think, pinouts as appropriate. resolved in e5b27a69645540cf2e75294163d82469aa2f1285 and 05506282c8ca8632f863e765d477157ff61a686f
