### ISSUE TITLE
add world plugs for power

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/cable-bible#8]
- [ ] Type A
- [ ] Type B
- [ ] Type C
- [ ] Type D
- [ ] Type E
- [ ] Type F
- [ ] Type G
- [ ] Type H
- [ ] Type I
- [ ] Type J
- [ ] Type K
- [ ] Type L
- [ ] Type M
- [ ] Type N

Not sure if we need to list them here, but a link to the IEC website would be useful: http://www.iec.ch/worldplugs/

**Comment by ablwr** [comment]
This is a very good resource!

**Comment by ablwr** [comment]
I'm in support of adding a link to this resource instead of replicating it within the bible.
